SELECT 
DISTINCT CRCC.CAR_ID
,CRCC.CAR_TYPE
    ,round(30*CRCC.DAILY_FEE*(100-CRCDP.DISCOUNT_RATE)/100) FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN 
    (
        SELECT 
        DISCOUNT_RATE
            ,CAR_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상'
    ) CRCDP
        ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
        AND CRCC.CAR_TYPE IN ('세단', 'SUV')
WHERE (CRCC.DAILY_FEE * 30 * (100-CRCDP.DISCOUNT_RATE)/100) >= 500000 
AND (CRCC.DAILY_FEE * 30 * (100-CRCDP.DISCOUNT_RATE)/100) <=2000000
AND CRCC.CAR_ID NOT IN
    (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
            AND END_DATE >= TO_DATE('2022-11-01','YYYY-MM-DD')
    )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC