-- 코드를 입력하세요
SELECT A.HOUR, COUNT(B.HOUR) COUNT
FROM 
    (SELECT LEVEL -1 AS HOUR FROM DUAL CONNECT BY LEVEL <=24 ) A
LEFT OUTER JOIN
    (SELECT TO_CHAR(DATETIME, 'HH24') HOUR FROM ANIMAL_OUTS ) B
ON A.HOUR = B.HOUR
GROUP BY A.HOUR
ORDER BY A.HOUR