-- 코드를 입력하세요
SELECT CAR_ID, round(avg(END_DATE-START_DATE)+1,1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having round(avg(END_DATE-START_DATE)+1,1) >= 7
order by AVERAGE_DURATION desc, car_id desc


-- select CAR_ID, END_DATE,START_DATE, (TO_DATE(to_char(END_DATE,'YYYYMMDD'),'YYYYMMDD')-TO_DATE(to_char(START_DATE,'YYYYMMDD'),'YYYYMMDD')) as AVERAGE_DURATION
-- from CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- order by CAR_ID