-- 코드를 입력하세요
SELECT P.PRODUCT_CODE,	(P.PRICE * NVL(S.SALES_AMOUNT,0)) SALES
FROM PRODUCT P LEFT OUTER JOIN 
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID)S
ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY 2 DESC, 1