-- 코드를 입력하세요
-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력
SELECT 
-- *
CRCRH.HISTORY_ID,
(CRCC.DAILY_FEE * (100-NVL(CCDP.DISCOUNT_RATE,0))/100 * CRCRH.DURATION) FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC 
JOIN 
(SELECT 
    HISTORY_ID,
    CAR_ID,
    (END_DATE-START_DATE+1)  DURATION, 
    CASE WHEN (END_DATE-START_DATE+1) >= 90 THEN '90일 이상'
    WHEN (END_DATE-START_DATE+1) >= 30 THEN '30일 이상'
    WHEN (END_DATE-START_DATE+1) >= 7 THEN '7일 이상'
        ELSE '' END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) CRCRH 
ON 
CRCC.CAR_ID = CRCRH.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CCDP
ON CRCC.CAR_TYPE = CCDP.CAR_TYPE
AND CCDP.DURATION_TYPE = CRCRH.DURATION_TYPE
WHERE CRCC.CAR_TYPE = '트럭' 
ORDER BY 2 DESC, 1 DESC
;


