-- 코드를 입력하세요
SELECT 
FP.PRODUCT_ID
,FP.PRODUCT_NAME
    ,(FP.PRICE * FO.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN 
    (SELECT 
     PRODUCT_ID
        ,SUM(AMOUNT) AMOUNT
     FROM FOOD_ORDER
     WHERE TO_CHAR(PRODUCE_DATE,'YYYYMM') = '202205'
     GROUP BY PRODUCT_ID) FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID