-- 코드를 입력하세요
SELECT 
A.APNT_NO	
,P.PT_NAME	
,P.PT_NO	
,A.MCDP_CD	
,D.DR_NAME	
    ,A.APNT_YMD
FROM APPOINTMENT A 
JOIN PATIENT P
    ON MCDP_CD = 'CS'
    AND APNT_CNCL_YN = 'N'
    AND TO_CHAR(APNT_YMD,'YYYYMMDD') = '20220413'
    AND A.PT_NO = P.PT_NO
JOIN DOCTOR D
    ON A.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD