-- 코드를 입력하세요
SELECT P.ID, P.NAME, TEMP.HOST_ID
FROM 
    (SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
     ) TEMP
JOIN PLACES P
ON TEMP.HOST_ID = P.HOST_ID
ORDER BY ID