-- 코드를 입력하세요
-- 
SELECT CAR_TYPE, COUNT(*) CARS
FROM CAR_RENTAL_COMPANY_CAR 
where REGEXP_LIKE (OPTIONS, '통풍시트|열선시트|가죽시트') 
-- WHERE OPTIONS LIKE '%가죽시트%'
--   OR OPTIONS LIKE '%열선시트%'
--   OR OPTIONS LIKE '%후방카메라%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;