-- -- 코드를 입력하세요
-- SELECT i.REST_ID,	i.REST_NAME,	i.FOOD_TYPE,	i.FAVORITES,	i.ADDRESS,	
-- (select round(avg(r.REVIEW_SCORE),2) REST_ID from REST_REVIEW r where r.REST_ID=i.REST_ID) SCORE
-- from REST_INFO i
-- where 1=1 and
-- A.ADDRESS Like '서울%'
-- order by SCORE desc, i.FAVORITES desc;

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
    , B.SCORE
FROM REST_INFO A, (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) B
WHERE 1=1 
AND A.REST_ID = B.REST_ID
AND A.ADDRESS LIKE '서울%'
ORDER BY B.SCORE DESC, A.FAVORITES DESC
;