-- 코드를 입력하세요
-- SELECT 
-- ANIMAL_ID
--     ,NAME
-- FROM ANIMAL_INS
-- WHERE REGEXP_LIKE(NAME, 'el', 'i')
-- ORDER BY NAME;

SELECT 
ANIMAL_ID
    ,NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog' 
AND LOWER(NAME) LIKE '%el%'
ORDER BY NAME;